// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgtQSJrAnkvzTlj-AtseB7RDenzzRDo84',
    appId: '1:253788510464:web:17cd2ce73c6e027d7ebbe5',
    messagingSenderId: '253788510464',
    projectId: 'my-pewar-project',
    authDomain: 'my-pewar-project.firebaseapp.com',
    storageBucket: 'my-pewar-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG_MuN3Z8X9zPWnkzgQO4t7dzebz5hWts',
    appId: '1:253788510464:android:a2c93a55c8df52d47ebbe5',
    messagingSenderId: '253788510464',
    projectId: 'my-pewar-project',
    storageBucket: 'my-pewar-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-6znRNkB0vgN9Gmg_3HoilAOhH1c-e0',
    appId: '1:253788510464:ios:b586e44f4a3278ed7ebbe5',
    messagingSenderId: '253788510464',
    projectId: 'my-pewar-project',
    storageBucket: 'my-pewar-project.firebasestorage.app',
    iosBundleId: 'com.example.application13',
  );
}
